In [3]:
import pandas as pd

In [9]:
df_empleados = pd.read_csv("/home/emmanuel/Descargas/Estructura_Organizacional.csv")
df_empleados
df_empleados[["apellido_paterno", "apellido_materno", "nombre"]] = df_empleados["NOMBRE"].str.split(n=2, expand=True)
df_empleados.drop(columns=["NOMBRE"], inplace=True)
# Insertar cada columna al inicio
df_empleados.insert(0, "nombre", df_empleados.pop("nombre"))
df_empleados.insert(0, "apellido_materno", df_empleados.pop("apellido_materno"))
df_empleados.insert(0, "apellido_paterno", df_empleados.pop("apellido_paterno"))

df_empleados

,apellido_paterno,apellido_materno,nombre,DPTO,correo,correo1,PROYECTO/AREA,SUBPROYECTO,BTA,JEFE INMEDIATO,...,%,IMSS,Asimilados,SINDICATO,VIATICOS/COMPLEMENTO DE PAGO,Factura,Hecuba,SUELDO BRUTO/MES,PERIODO DE PAGO,DIVISA
0,ESCUTIA,SANTILLANA,JUAN,Operations,juan.escutia@tusalfin.com,juan.escutia@tusalfin.com,HWMX1801RDD-Recursos RAN GSC (Reportes RF) - H...,RAN GSC,RAN-GSC - HWMX1801RDD,ELIZABETH VALDIVIA,...,100% Pago Por Reporte (FACTURACION ),NaN,NaN,NaN,NaN,PAGO POR REPORTE,NaN,PAGO POR REPORTE,QUINCENAL,MXN
1,MARTINEZ,CAMPOS,RICARDO,Operations,ricardo.martinez@tusalfin.com,ricardo.martinez@tusalfin.com,HWMX1801RDD-Recursos RAN GSC (Reportes RF) - H...,RAN GSC,RAN-GSC - HWMX1801RDD,ELIZABETH VALDIVIA,...,100% Pago Por Reporte (FACTURACION ),NaN,NaN,NaN,NaN,PAGO POR REPORTE,NaN,PAGO POR REPORTE,QUINCENAL,MXN
2,LOPEZ,SANABRIA,IRAIS YAJAIRA,Operations,irais.lopez@tusalfin.com,irais.lopez@tusalfin.com,HWMX1801RDD-Recursos RAN GSC (Reportes RF) - H...,RAN GSC,RAN-GSC - HWMX1801RDD,ELIZABETH VALDIVIA,...,100% Pago Por Reporte (FACTURACION ),NaN,NaN,NaN,NaN,PAGO POR REPORTE,NaN,PAGO POR REPORTE,QUINCENAL,MXN
3,GARCIA,SALINAS,FERNANDO,Operations,fernando.garcia@tusalfin.com,fernando.garcia@tusalfin.com,HWMX1801RDD-Recursos RAN GSC (Reportes RF) - H...,RAN GSC,RAN-GSC - HWMX1801RDD,ELIZABETH VALDIVIA,...,100% Pago Por Reporte (FACTURACION ),NaN,NaN,NaN,NaN,PAGO POR REPORTE,NaN,PAGO POR REPORTE,QUINCENAL,MXN
4,ARAGON,CRUZ,SERVANDO,Operations,servando.aragon@tusalfin.com,servando.aragon@tusalfin.com,HWMX2001CST-Proyecto TE Huawei GSC Queretaro s...,MBB,GSC-TE-MBB -HWMX2001CST,ELIZABETH VALDIVIA,...,100% Pago Por Reporte (FACTURACION ),NaN,NaN,NaN,NaN,PAGO POR REPORTE,NaN,PAGO POR REPORTE,QUINCENAL,MXN
5,MORALES,RAMIREZ,GRISEL,Operations,grisel.morales@tusalfin.com,grisel.morales@tusalfin.com,HWMX2001CST-Proyecto TE Huawei GSC Queretaro s...,MBB,GSC-TE-MBB -HWMX2001CST,ELIZABETH VALDIVIA,...,100% Pago Por Reporte (Sindicato),-,NaN,NaN,PAGO POR REPORTE,-,NaN,PAGO POR REPORTE,QUINCENAL,MXN
6,VALDIVIA,ALANIS,MARIO ALBERTO,Operations,mario.valdivia@tusalfin.com,mario.valdivia@tusalfin.com,HWMX2001CST-Proyecto TE Huawei GSC Queretaro s...,MBB,GSC-TE-MBB -HWMX2001CST,ELIZABETH VALDIVIA,...,100% Pago Por Reporte (FACTURACION ),NaN,NaN,NaN,NaN,18000 +PAGO POR REPORTE,NaN,"18,000 + PAGO POR REPORTE",QUINCENAL,MXN
7,MADRIGAL,LOPEZ,SONIA,Operations,sonia.madrigal@tusalfin.com,sonia.madrigal@tusalfin.com,HWMX2001CST-Proyecto TE Huawei GSC Queretaro s...,MBB,GSC-TE-MBB -HWMX2001CST,ELIZABETH VALDIVIA,...,100% Pago Por Reporte (Sindicato),NaN,NaN,NaN,PAGO POR REPORTE,NaN,NaN,PAGO POR REPORTE,QUINCENAL,MXN
8,RESENDIZ,BARRERA,ALFREDO,Operations,alfredo.resendiz@tusalfin.com,alfredo.resendiz@tusalfin.com,HWMX2404SCD-Subcontracting GSC - DOC,DOC - GSC,DOC - GSC- HWMX2404SCD,MASTERTON JAIMES,...,100% (FACTURACION),NaN,NaN,NaN,NaN,"$17,334.00",NaN,"$17,334.00",QUINCENAL,MXN
9,PRADO,LOPEZ,ANDREI,Operations,andrei.prado@tusalfin.com,andrei.prado@tusalfin.com,HWMX2404SCD-Subcontracting GSC - DOC,DOC - GSC,DOC - GSC- HWMX2404SCD,MASTERTON JAIMES,...,100% (FACTURACION),NaN,NaN,NaN,NaN,"$20,240.00",NaN,"$20,240.00",QUINCENAL,MXN
10,CARRILLO,FRIAS,BRYAN,Operations,bryan.carrillo@tusalfin.com,bryan.carrillo@tusalfin.com,HWMX2404SCD-Subcontracting GSC - DOC,DOC - GSC,DOC - GSC- HWMX2404SCD,MASTERTON JAIMES,...,100% (FACTURACION),NaN,NaN,NaN,NaN,"$20,437.00",NaN,"$20,437.00",QUINCENAL,MXN
11,PEREZ,SILVA,GABRIEL,Operations,gabriel.perez@tusalfin.com,gabriel.perez@tusalfin.com,HWMX2404SCD-Subcontracting GSC - DOC,DOC - GSC,DOC - GSC- HWMX2404SCD,MASTERTON JAIMES,...,100% (FACTURACION),NaN,NaN,NaN,NaN,"$23,575.00",NaN,"$23,575.00",QUINCENAL,MXN

In [8]:
json_empleados = df_empleados.to_dict(orient="records")
i = 8
for empleado in json_empleados[2:]:
    print(empleado)
    print(empleado.get("correo"))

    # respuesta = alta_empleado(
    #     no_empleado=8,
    #     primer_nombre=empleado.get("nombre"),
    #     apellido_materno=empleado.get("apellido_materno"),
    #     apellido_paterno=empleado.get("apellido_paterno"),
    #     email_personal= get("correo"),
    #     email_empresa=  correo,
    #     rfc="XXXX900903X6"+"i+1",
    #     curp="XXXXXXXXXXX"+"i",
        
    # )
    i = i + 1

{'apellido_paterno': 'LOPEZ', 'apellido_materno': 'SANABRIA', 'nombre': 'IRAIS YAJAIRA ', 'DPTO': 'Operations', 'correo': 'irais.lopez@tusalfin.com', 'PROYECTO/AREA': 'HWMX1801RDD-Recursos RAN GSC (Reportes RF) - Huawei', 'SUBPROYECTO': 'RAN GSC', 'BTA': 'RAN-GSC - HWMX1801RDD', 'JEFE INMEDIATO': 'ELIZABETH VALDIVIA ', 'CLIENTE': 'HUAWEI', 'PUESTO': 'Ingeniero RF', 'EMPLEADOR': 'GTA', 'EMPRESA PAGADORA': 'GTA', 'ESQUEMA': 'Prestaci�n De Servicios (Facturaci�n) Pago Por Reporte', '%': '100%   Pago Por Reporte  (FACTURACION )', ' IMSS': nan, 'Asimilados': nan, 'SINDICATO': nan, 'VIATICOS/COMPLEMENTO DE PAGO': nan, 'Factura': ' PAGO POR REPORTE  ', 'Hecuba': nan, 'SUELDO BRUTO/MES': '  PAGO POR REPORTE ', 'PERIODO DE PAGO ': ' QUINCENAL ', 'DIVISA': 'MXN'}
irais.lopez@tusalfin.com
{'apellido_paterno': 'GARCIA', 'apellido_materno': 'SALINAS', 'nombre': 'FERNANDO  ', 'DPTO': 'Operations', 'correo': 'fernando.garcia@tusalfin.com', 'PROYECTO/AREA': 'HWMX1801RDD-Recursos RAN GSC (Reportes RF) - Huawei', 'SUBPROYECTO': 'RAN GSC', 'BTA': 'RAN-GSC - HWMX1801RDD', 'JEFE INMEDIATO': 'ELIZABETH VALDIVIA ', 'CLIENTE': 'HUAWEI', 'PUESTO': 'Ingeniero RF', 'EMPLEADOR': 'GTA', 'EMPRESA PAGADORA': 'GTA', 'ESQUEMA': 'Prestaci�n De Servicios (Facturaci�n) Pago Por Reporte', '%': '100%   Pago Por Reporte  (FACTURACION )', ' IMSS': nan, 'Asimilados': nan, 'SINDICATO': nan, 'VIATICOS/COMPLEMENTO DE PAGO': nan, 'Factura': ' PAGO POR REPORTE  ', 'Hecuba': nan, 'SUELDO BRUTO/MES': '  PAGO POR REPORTE ', 'PERIODO DE PAGO ': ' QUINCENAL ', 'DIVISA': 'MXN'}
fernando.garcia@tusalfin.com
{'apellido_paterno': 'ARAGON', 'apellido_materno': 'CRUZ', 'nombre': 'SERVANDO  ', 'DPTO': 'Operations', 'correo': 'servando.aragon@tusalfin.com', 'PROYECTO/AREA': 'HWMX2001CST-Proyecto TE Huawei GSC Queretaro servicios', 'SUBPROYECTO': 'MBB', 'BTA': 'GSC-TE-MBB -HWMX2001CST', 'JEFE INMEDIATO': 'ELIZABETH VALDIVIA ', 'CLIENTE': 'HUAWEI', 'PUESTO': 'Consultor MBB', 'EMPLEADOR': 'GTA', 'EMPRESA PAGADORA': 'GTA ', 'ESQUEMA': 'Prestaci�n De Servicios (Facturaci�n) Pago Por Reporte', '%': '100%   Pago Por Reporte  (FACTURACION )', ' IMSS': nan, 'Asimilados': nan, 'SINDICATO': nan, 'VIATICOS/COMPLEMENTO DE PAGO': nan, 'Factura': ' PAGO POR REPORTE  ', 'Hecuba': nan, 'SUELDO BRUTO/MES': ' PAGO POR REPORTE ', 'PERIODO DE PAGO ': ' QUINCENAL ', 'DIVISA': 'MXN'}
servando.aragon@tusalfin.com
{'apellido_paterno': 'MORALES', 'apellido_materno': 'RAMIREZ', 'nombre': 'GRISEL  ', 'DPTO': 'Operations', 'correo': 'grisel.morales@tusalfin.com', 'PROYECTO/AREA': 'HWMX2001CST-Proyecto TE Huawei GSC Queretaro servicios', 'SUBPROYECTO': 'MBB', 'BTA': 'GSC-TE-MBB -HWMX2001CST', 'JEFE INMEDIATO': 'ELIZABETH VALDIVIA ', 'CLIENTE': 'HUAWEI', 'PUESTO': 'Consultor MBB', 'EMPLEADOR': 'GTA', 'EMPRESA PAGADORA': 'PROV ALCE', 'ESQUEMA': 'Prestaci�n De Servicios (Sindicato ) Pago Por Reporte', '%': '100%   Pago Por Reporte  (Sindicato)', ' IMSS': ' - ', 'Asimilados': nan, 'SINDICATO': nan, 'VIATICOS/COMPLEMENTO DE PAGO': ' PAGO POR REPORTE  ', 'Factura': ' - ', 'Hecuba': nan, 'SUELDO BRUTO/MES': ' PAGO POR REPORTE  ', 'PERIODO DE PAGO ': ' QUINCENAL ', 'DIVISA': 'MXN'}
grisel.morales@tusalfin.com
{'apellido_paterno': 'VALDIVIA', 'apellido_materno': 'ALANIS', 'nombre': 'MARIO ALBERTO ', 'DPTO': 'Operations', 'correo': 'mario.valdivia@tusalfin.com', 'PROYECTO/AREA': 'HWMX2001CST-Proyecto TE Huawei GSC Queretaro servicios', 'SUBPROYECTO': 'MBB', 'BTA': 'GSC-TE-MBB -HWMX2001CST', 'JEFE INMEDIATO': 'ELIZABETH VALDIVIA ', 'CLIENTE': 'HUAWEI', 'PUESTO': 'Consultor MBB', 'EMPLEADOR': 'GTA', 'EMPRESA PAGADORA': 'GTA', 'ESQUEMA': 'Prestaci�n De Servicios (Facturaci�n) Pago Por Reporte', '%': '100%   Pago Por Reporte  (FACTURACION )', ' IMSS': nan, 'Asimilados': nan, 'SINDICATO': nan, 'VIATICOS/COMPLEMENTO DE PAGO': nan, 'Factura': ' 18000 +PAGO POR REPORTE  ', 'Hecuba': nan, 'SUELDO BRUTO/MES': ' 18,000 + PAGO POR REPORTE ', 'PERIODO DE PAGO ': ' QUINCENAL ', 'DIVISA': 'MXN'}
mario.valdivia@tusalfin.com
{'apellido_paterno': 'MADRIGAL', 'apellido_materno': 'LOPEZ', 'nombre': 'SONIA  ', 'DPTO': 'Operations', 'correo': 'sonia.madrigal@tusalfin.com', 'PROYECTO/AREA': 'HWMX2001CST-Proyecto TE Huawei GSC Queretaro servicios', 'SUBPROYECTO': 'MBB', 'BTA': 'GSC-TE-MBB -HWMX2001CST', 'JEFE INMEDIATO': 'ELIZABETH VALDIVIA ', 'CLIENTE': 'HUAWEI', 'PUESTO': 'Consultor MBB', 'EMPLEADOR': 'GTA', 'EMPRESA PAGADORA': 'PROV ALCE', 'ESQUEMA': 'Prestaci�n De Servicios (Sindicato ) Pago Por Reporte', '%': '100%   Pago Por Reporte  (Sindicato)', ' IMSS': nan, 'Asimilados': nan, 'SINDICATO': nan, 'VIATICOS/COMPLEMENTO DE PAGO': ' PAGO POR REPORTE  ', 'Factura': nan, 'Hecuba': nan, 'SUELDO BRUTO/MES': ' PAGO POR REPORTE  ', 'PERIODO DE PAGO ': ' QUINCENAL ', 'DIVISA': 'MXN'}
sonia.madrigal@tusalfin.com
{'apellido_paterno': 'RESENDIZ', 'apellido_materno': 'BARRERA', 'nombre': 'ALFREDO ', 'DPTO': 'Operations', 'correo': 'alfredo.resendiz@tusalfin.com', 'PROYECTO/AREA': 'HWMX2404SCD-Subcontracting GSC - DOC', 'SUBPROYECTO': 'DOC - GSC', 'BTA': 'DOC - GSC- HWMX2404SCD', 'JEFE INMEDIATO': 'MASTERTON JAIMES ', 'CLIENTE': 'HUAWEI', 'PUESTO': 'CONSULTOR', 'EMPLEADOR': 'GTA', 'EMPRESA PAGADORA': 'GTA', 'ESQUEMA': 'Prestaci�n De Servicios (Facturaci�n)', '%': '100%   (FACTURACION)', ' IMSS': nan, 'Asimilados': nan, 'SINDICATO': nan, 'VIATICOS/COMPLEMENTO DE PAGO': nan, 'Factura': ' $17,334.00 ', 'Hecuba': nan, 'SUELDO BRUTO/MES': ' $17,334.00 ', 'PERIODO DE PAGO ': ' QUINCENAL ', 'DIVISA': 'MXN'}
alfredo.resendiz@tusalfin.com
{'apellido_paterno': 'PRADO', 'apellido_materno': 'LOPEZ', 'nombre': 'ANDREI ', 'DPTO': 'Operations', 'correo': 'andrei.prado@tusalfin.com', 'PROYECTO/AREA': 'HWMX2404SCD-Subcontracting GSC - DOC', 'SUBPROYECTO': 'DOC - GSC', 'BTA': 'DOC - GSC- HWMX2404SCD', 'JEFE INMEDIATO': 'MASTERTON JAIMES ', 'CLIENTE': 'HUAWEI', 'PUESTO': 'CONSULTOR', 'EMPLEADOR': 'GTA', 'EMPRESA PAGADORA': 'GTA', 'ESQUEMA': 'Prestaci�n De Servicios (Facturaci�n)', '%': '100%   (FACTURACION)', ' IMSS': nan, 'Asimilados': nan, 'SINDICATO': nan, 'VIATICOS/COMPLEMENTO DE PAGO': nan, 'Factura': ' $20,240.00 ', 'Hecuba': nan, 'SUELDO BRUTO/MES': ' $20,240.00 ', 'PERIODO DE PAGO ': ' QUINCENAL ', 'DIVISA': 'MXN'}
andrei.prado@tusalfin.com
{'apellido_paterno': 'CARRILLO', 'apellido_materno': 'FRIAS', 'nombre': 'BRYAN ', 'DPTO': 'Operations', 'correo': 'bryan.carrillo@tusalfin.com', 'PROYECTO/AREA': 'HWMX2404SCD-Subcontracting GSC - DOC', 'SUBPROYECTO': 'DOC - GSC', 'BTA': 'DOC - GSC- HWMX2404SCD', 'JEFE INMEDIATO': 'MASTERTON JAIMES ', 'CLIENTE': 'HUAWEI', 'PUESTO': 'CONSULTOR', 'EMPLEADOR': 'GTA', 'EMPRESA PAGADORA': 'GTA', 'ESQUEMA': 'Prestaci�n De Servicios (Facturaci�n)', '%': '100%   (FACTURACION)', ' IMSS': nan, 'Asimilados': nan, 'SINDICATO': nan, 'VIATICOS/COMPLEMENTO DE PAGO': nan, 'Factura': ' $20,437.00 ', 'Hecuba': nan, 'SUELDO BRUTO/MES': ' $20,437.00 ', 'PERIODO DE PAGO ': ' QUINCENAL ', 'DIVISA': 'MXN'}
bryan.carrillo@tusalfin.com
{'apellido_paterno': 'PEREZ', 'apellido_materno': 'SILVA', 'nombre': 'GABRIEL ', 'DPTO': 'Operations', 'correo': 'gabriel.perez@tusalfin.com', 'PROYECTO/AREA': 'HWMX2404SCD-Subcontracting GSC - DOC', 'SUBPROYECTO': 'DOC - GSC', 'BTA': 'DOC - GSC- HWMX2404SCD', 'JEFE INMEDIATO': 'MASTERTON JAIMES ', 'CLIENTE': 'HUAWEI', 'PUESTO': 'TECHNICAL ENGINEER', 'EMPLEADOR': 'GTA', 'EMPRESA PAGADORA': 'GTA', 'ESQUEMA': 'Prestaci�n De Servicios (Facturaci�n)', '%': '100%   (FACTURACION)', ' IMSS': nan, 'Asimilados': nan, 'SINDICATO': nan, 'VIATICOS/COMPLEMENTO DE PAGO': nan, 'Factura': ' $23,575.00 ', 'Hecuba': nan, 'SUELDO BRUTO/MES': ' $23,575.00 ', 'PERIODO DE PAGO ': ' QUINCENAL ', 'DIVISA': 'MXN'}
gabriel.perez@tusalfin.com

In [ ]:
import requests
import pandas as pd

#
USERNAME = f'gta_qas@gta.com.mx'
PASSWORD = f'wW94;6mog[hc'
BASE_URL = f'http://18.217.164.177:8001'

def get_token(usr, password):
    json_data  = {
                "username":  usr,
                "password": password
    }
    url = BASE_URL + '/api/token/'
    response = requests.post(url, data=json_data)
    if response.status_code == 200:
        response_json = response.json()
        token = response_json.get('access')
        return token

def alta_empleado(no_empleado,primer_nombre, apellido_paterno, apellido_materno, correo, rfc, curp):
    json_data =  {
            "no_empleado": no_empleado,
            "nombres": primer_nombre,
            "apellido_paterno":apellido_paterno,
            "apellido_materno": apellido_materno,
            "estado_fsm": "alta",
            "no_celular": "5551234567",
            "email_personal": correo,
            "email_empresa":  correo,
            "rfc":rfc,
            "curp": curp,
            "tipo_nomina": 1,
            "clave_internacional": "+52",
            "clabe_interbancaria": "777777777777777777",
            "no_cuenta": "7777777777777",
            "no_seguro_social": "7777777777777",
            "banco_cuenta": "3",
            "activo": True,
            "imagen": None,
            "fecha_ingreso": None,
            "fecha_baja": None,
            "fecha_creacion": "2024-11-12T13:47:38.482400-06:00",
            "fecha_modificacion": "2024-11-12T13:47:38.482422-06:00",
    }
    
    url = BASE_URL + '/api/empleados/'
    token = get_token(USERNAME,PASSWORD)
    headers = {
            'Content-Type': 'application/json',
            'Authorization':  f"Bearer {token}"
            }
    print(headers)
    response = requests.post(url, 
                             json=json_data,
                             headers=headers
                             )

    if response.status_code == 200:
        response_json = response.json()
        return response_json
    else:
        return response.json()
    
def actualizar_empleado(id_empleado, proyecto):
    """Actualiza un empleado agregándole un proyecto."""
    url = f"{BASE_URL}/api/empleado/edit-empleado/{id_empleado}/"  # URL correcta
    token = get_token(USERNAME, PASSWORD)
    
    if not token:
        print("Error: No se pudo obtener el token de autenticación.")
        return
    
    headers = {
        'Content-Type': 'application/json',
        'Authorization': f"Bearer {token}"
    }
    
    json_data = {
        "proyecto": proyecto  # Nombre del campo a actualizar
    }

    response = requests.patch(url, json=json_data, headers=headers)

    if response.status_code in [200, 201]:
        print(f"Empleado {id_empleado} actualizado con el proyecto {proyecto}.")
        return response.json()
    else:
        print(f"Error al actualizar empleado {id_empleado}: {response.status_code}")
        print(response.text)

# Llamada a la función para actualizar el empleado con un proyecto
actualizar_empleado(id_empleado=8, proyecto="Proyecto X")

In [18]:
import string
import random
def generar_rfc_unico(primer_nombre, apellido_paterno, apellido_materno):
    # Tomar las primeras letras del apellido paterno, materno y nombre
    rfc_base = (
        apellido_paterno[:2].upper() +  # Primeras 2 letras del apellido paterno
        apellido_materno[:1].upper() +  # Primera letra del apellido materno
        primer_nombre[:1].upper()       # Primera letra del nombre
    )
    
    # Generar un sufijo aleatorio de 6 dígitos
    sufijo = ''.join(random.choices(string.digits, k=6))
    
    # Combinar para formar el RFC completo
    rfc = (rfc_base + sufijo).ljust(13, 'X')  # Rellenar con 'X' si es necesario
    
    # Verificar que el RFC no esté duplicado
    # while rfc in rfc_existentes:
    #     sufijo = ''.join(random.choices(string.digits, k=6))
    #     rfc = (rfc_base + sufijo).ljust(13, 'X')
    
    # Agregar el RFC a la lista de existentes
    # rfc_existentes.add(rfc)
    return rfc
rfc = generar_rfc_unico(
        primer_nombre=empleado.get("nombre"),
        apellido_paterno=empleado.get("apellido_paterno"),
        apellido_materno=empleado.get("apellido_materno"),
    )
print(rfc)

PESG121167XXX

In [4]:
import requests

# Clave de la API (debes obtenerla registrándote en la API)
API_KEY = 'd527519e11msh7ce963ccbe620b9p10158ejsn257bb56b98a2'

# URL de la API para obtener datos de partidos en vivo
url = f'https://api-football-v1.p.rapidapi.com/v3/fixtures?live=all'
headers = {
    'x-rapidapi-key': API_KEY,
    'x-rapidapi-host': 'api-football-v1.p.rapidapi.com'
}

# Hacer la solicitud a la API
response = requests.get(url, headers=headers)
data = response.json()

# Verificar si la solicitud fue exitosa
if response.status_code == 200:
    print("Solicitud exitosa")
    print(data)  # Imprimir la respuesta completa
else:
    print(f"Error en la solicitud: {response.status_code}")
    print(data)  # Imprimir la respuesta para ver el mensaje de error
# # Filtrar partidos
# for partido in data['response']:
#     equipo_local = partido['teams']['home']['name']
#     equipo_visitante = partido['teams']['away']['name']
#     tarjetas_rojas_local = partido['statistics']['home']['red_cards']
#     tarjetas_rojas_visitante = partido['statistics']['away']['red_cards']
#     marcador_local = partido['goals']['home']
#     marcador_visitante = partido['goals']['away']

#     # Verificar condiciones
#     if (tarjetas_rojas_local >= 1 and marcador_local == 1 and marcador_visitante == 0) or \
#        (tarjetas_rojas_visitante >= 1 and marcador_visitante == 1 and marcador_local == 0):
#         print(f"Partido: {equipo_local} vs {equipo_visitante}")
#         print(f"Tarjetas rojas local: {tarjetas_rojas_local}")
#         print(f"Tarjetas rojas visitante: {tarjetas_rojas_visitante}")
#         print(f"Marcador: {marcador_local}-{marcador_visitante}")
#         print("-" * 30)

Solicitud exitosa

In [24]:

url = f'https://api-football-v1.p.rapidapi.com/v3/fixtures?live=all'
headers = {
    'x-rapidapi-key': API_KEY,
    'x-rapidapi-host': 'api-football-v1.p.rapidapi.com'
}

# Hacer la solicitud a la API
response = requests.get(url, headers=headers)
data = response.json()

# # Verificar si la solicitud fue exitosa
# if response.status_code == 200:
#     print("Solicitud exitosa")
#     if data['response']:
#         print("Partidos en vivo:")
#         for partido in data['response']:
#             partido_id = partido['fixture']['id']
#             equipo_local = partido['teams']['home']['name']
#             equipo_visitante = partido['teams']['away']['name']
#             marcador_local = partido['goals']['home']
#             marcador_visitante = partido['goals']['away']
#             print(f"ID: {partido_id}, Partido: {equipo_local} {marcador_local}-{marcador_visitante} {equipo_visitante}")
#     else:
#         print("No hay partidos en vivo en este momento.")
# else:
#     print(f"Error en la solicitud: {response.status_code}")
#     print(data)  # Imprimir la respuesta para ver el mensaje de 
    
if response.status_code == 200:
    print("Solicitud exitosa")
    if data['response']:
        print("Partidos en vivo:")
        for partido in data['response']:
            # Acceder al ID del partido
            partido_id = partido['fixture']['id']
            
            # Acceder a los nombres de los equipos
            equipo_local = partido['teams']['home']['name']
            equipo_visitante = partido['teams']['away']['name']
            
            # Acceder al marcador
            marcador_local = partido['goals']['home']
            marcador_visitante = partido['goals']['away']
            
            # Imprimir la información del partido
            print(f"ID: {partido_id}, Partido: {equipo_local} {marcador_local}-{marcador_visitante} {equipo_visitante}")
    else:
        print("No hay partidos en vivo en este momento.")
else:
    print(f"Error en la solicitud: {response.status_code}")
    print(data)  # Imprimir la respuesta para ver el mensaje de error

Solicitud exitosa
Partidos en vivo:
ID: 1306253, Partido: Toulde 0-1 Tevragh-Zeïne
ID: 1334070, Partido: Juticalpa 1-0 CD Olimpia
ID: 1336351, Partido: Real Soacha 2-0 Depor FC
ID: 1347523, Partido: Central Córdoba SdE Res. 0-0 Newell's Old Boys Res.
ID: 1355036, Partido: remo 0-0 Criciuma
ID: 1355040, Partido: Alianza Lima 0-0 Deportes Iquique
ID: 1355627, Partido: CEOV Operário 0-0 Novorizontino
ID: 1258324, Partido: Helston Athletic 2-8 Cinderford Town
ID: 1259341, Partido: Sittingbourne 3-1 Littlehampton Town
ID: 1349951, Partido: RC Kouba 0-1 USM Alger
ID: 1350520, Partido: Deportivo Pasto W 1-0 Junior W
ID: 1353179, Partido: Liverpool 0-1 Paris Saint Germain
ID: 1352884, Partido: Al Taawon 2-2 Tractor Sazi

In [56]:
import requests

# Clave de la API (debes obtenerla registrándote en la API)
API_KEY = 'd527519e11msh7ce963ccbe620b9p10158ejsn257bb56b98a2'  # Reemplaza con tu API Key

# URL de la API para obtener partidos en vivo
url_partidos = "https://v3.football.api-sports.io/fixtures?live=all"
headers = {
    'x-rapidapi-key': API_KEY,
    'x-rapidapi-host': 'api-football-v1.p.rapidapi.com'
}

# Hacer la solicitud a la API para obtener partidos en vivo
response_partidos = requests.get(url_partidos, headers=headers)
data_partidos = response_partidos.json()

# Verificar si la solicitud fue exitosa
if response_partidos.status_code == 200:
    print("Solicitud exitosa")
    if data_partidos['response']:
        # Iterar sobre cada partido en vivo
        lista_de_partidos = []
        for partido in data_partidos['response']:
            partido_id = partido['fixture']['id']
            equipo_local = partido['teams']['home']['name']
            equipo_visitante = partido['teams']['away']['name']
            marcador_local = partido['goals']['home']
            marcador_visitante = partido['goals']['away']

            lista_de_partidos.append({
                "Partido_ID": partido_id,
                "Equipo_Local": equipo_local,
                "Equipo_Visitante": equipo_visitante,
                "Goles_Local": marcador_local,
                "Goles_Visitante": marcador_visitante
            })

            # Obtener eventos del partido
            url_eventos = f'https://api-football-v1.p.rapidapi.com/v3/fixtures/events?search={partido_id}'
            response_eventos = requests.get(url_eventos, headers=headers)
            data_eventos = response_eventos.json()

            # Verificar si la solicitud de eventos fue exitosa
            if response_eventos.status_code == 200 and data_eventos['response']:
                # Filtrar tarjetas rojas
                tarjetas_rojas = []
                for evento in data_eventos['response']:
                    if evento.get('type') == 'Card' and evento.get('detail') == 'Red Card':
                        equipo = evento['team']['name']
                        jugador = evento['player']['name'] if evento['player'] else 'Desconocido'
                        tiempo = evento['time']['elapsed']
                        tarjetas_rojas.append((equipo, jugador, tiempo))

                # Mostrar tarjetas rojas
                if tarjetas_rojas:
                    print("Tarjetas rojas en este partido:")
                    for equipo, jugador, tiempo in tarjetas_rojas:
                        print(f"  - {equipo}: {jugador} (minuto {tiempo}')")
                else:
                    print("  No hay tarjetas rojas en este partido.")
            else:
                print("  No se pudieron obtener los eventos del partido.")
    else:
        print("No hay partidos en vivo en este momento.")
else:
    print(f"Error en la solicitud: {response_partidos.status_code}")
    data_partidos  # Imprimir la respuesta para ver el mensaje de error

df_futbol = pd.DataFrame(lista_de_partidos)
df_futbol

Solicitud exitosa
No hay partidos en vivo en este momento.

,Partido_ID,Equipo_Local,Equipo_Visitante,Goles_Local,Goles_Visitante
0,1258324,Helston Athletic,Cinderford Town,2,8
1,1259341,Sittingbourne,Littlehampton Town,3,1

In [30]:
len(data_partidos)

6

In [1]:
import requests
from bs4 import BeautifulSoup

# URL de búsqueda en Google
url = "https://www.google.com/search?q=liga+mx"

# Headers para simular un navegador real
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
}

# Realizar la solicitud HTTP
response = requests.get(url, headers=headers)

# Verificar si la solicitud fue exitosa
if response.status_code == 200:
    # Analizar el HTML con BeautifulSoup
    soup = BeautifulSoup(response.text, 'html.parser')

    # Extraer títulos de los resultados
    for resultado in soup.find_all('h3'):
        print(resultado.text)
else:
    print(f"Error al acceder a la página: {response.status_code}")

In [4]:
from selenium import webdriver
from selenium.webdriver.common.by import By
import time

# Configurar el navegador
options = webdriver.ChromeOptions()
options.add_argument('--headless')  # Ejecutar en modo sin interfaz gráfica
options.add_argument('--disable-gpu')
options.add_argument('--no-sandbox')

# Ruta al ChromeDriver
driver_path = 'ruta/al/chromedriver'

# Iniciar el navegador
driver = webdriver.Chrome(executable_path=driver_path, options=options)

# URL de búsqueda en Google
url = "https://www.google.com/search?q=liga+mx"

# Abrir la página
driver.get(url)

# Esperar a que la página cargue
time.sleep(3)

# Extraer títulos de los resultados
resultados = driver.find_elements(By.CSS_SELECTOR, 'h3')
for resultado in resultados:
    print(resultado.text)

# Cerrar el navegador
driver.quit()

TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'

In [6]:
import requests

# Clave de la API y ID del motor de búsqueda
API_KEY = 'AIzaSyBVA7STURxAIV0nn9Bj_y0Ux_-OmFkUYDk'
CSE_ID = 'e3563b68f68eb43e0'

# Término de búsqueda
query = 'chivas vs america'

# URL de la API de Google Custom Search
url = f'https://www.googleapis.com/customsearch/v1?q={query}&key={API_KEY}&cx={CSE_ID}'

# Hacer la solicitud
response = requests.get(url)
data = response.json()

# Mostrar resultados
if 'items' in data:
    for item in data['items']:
        print(f"Título: {item['title']}")
        print(f"Enlace: {item['link']}")
        print("-" * 30)
else:
    print("No se encontraron resultados o hubo un error en la solicitud.")

No se encontraron resultados o hubo un error en la solicitud.

In [49]:
import pandas as pd
#pd.DataFrame(data_partidos)
partidos_lista = []  # Lista vacía

for partido in data_partidos['response']:
    partido_id = partido['fixture']['id']
    equipo_local = partido['teams']['home']['name']
    equipo_visitante = partido['teams']['away']['name']
    marcador_local = partido['goals']['home']
    marcador_visitante = partido['goals']['away']

    # Agregar a la lista como un diccionario
    partidos_lista.append({
        "Partido ID": partido_id,
        "Local": equipo_local,
        "Visitante": equipo_visitante,
        "Marcador": f"{marcador_local}-{marcador_visitante}"
    })

# Ver la lista de partidos guardados
print(partidos_lista)

[{'Partido ID': 1323637, 'Local': 'Santos AP', 'Visitante': 'Ypiranga-PE', 'Marcador': '0-0'}, {'Partido ID': 1355036, 'Local': 'remo', 'Visitante': 'Criciuma', 'Marcador': '0-1'}, {'Partido ID': 1258324, 'Local': 'Helston Athletic', 'Visitante': 'Cinderford Town', 'Marcador': '2-8'}, {'Partido ID': 1259341, 'Local': 'Sittingbourne', 'Visitante': 'Littlehampton Town', 'Marcador': '3-1'}, {'Partido ID': 1306253, 'Local': 'Toulde', 'Visitante': 'Tevragh-Zeïne', 'Marcador': '0-1'}, {'Partido ID': 1334070, 'Local': 'Juticalpa', 'Visitante': 'CD Olimpia', 'Marcador': '1-0'}, {'Partido ID': 1347523, 'Local': 'Central Córdoba SdE Res.', 'Visitante': "Newell's Old Boys Res.", 'Marcador': '0-0'}, {'Partido ID': 1350520, 'Local': 'Deportivo Pasto W', 'Visitante': 'Junior W', 'Marcador': '1-1'}, {'Partido ID': 1355627, 'Local': 'CEOV Operário', 'Visitante': 'Novorizontino', 'Marcador': '0-1'}, {'Partido ID': 1336351, 'Local': 'Real Soacha', 'Visitante': 'Depor FC', 'Marcador': '4-1'}, {'Partido ID': 1355040, 'Local': 'Alianza Lima', 'Visitante': 'Deportes Iquique', 'Marcador': '1-0'}]

In [54]:
import pandas as pd

partidos_lista = []  # Lista vacía

for partido in data_partidos['response']:
    partido_id = partido['fixture']['id']
    equipo_local = partido['teams']['home']['name']
    equipo_visitante = partido['teams']['away']['name']
    marcador_local = partido['goals']['home']
    marcador_visitante = partido['goals']['away']

    # Agregar a la lista como un diccionario
    partidos_lista.append({
        "Partido_ID": partido_id,
        "Equipo_Local": equipo_local,
        "Equipo_Visitante": equipo_visitante,
        "Goles_Local": marcador_local,
        "Goles_Visitante": marcador_visitante
    })

# Convertir la lista de diccionarios en un DataFrame
df_partidos = pd.DataFrame(partidos_lista)

# Mostrar el DataFrame
df_partidos

,Partido_ID,Equipo_Local,Equipo_Visitante,Goles_Local,Goles_Visitante
0,1258324,Helston Athletic,Cinderford Town,2,8
1,1259341,Sittingbourne,Littlehampton Town,3,1

{'get': 'fixtures', 'parameters': {'live': 'all'}, 'errors': {'token': 'Error/Missing application key. Go to https://www.api-football.com/documentation-v3 to learn how to get your API application key.'}, 'results': 0, 'paging': {'current': 1, 'total': 1}, 'response': []}

# ESPN API 
https://github.com/pseudo-r/Public-ESPN-API

In [57]:
import requests

# URL para obtener partidos en vivo de ESPN (puede cambiar con el tiempo)
url = "https://site.api.espn.com/apis/site/v2/sports/soccer/scoreboard"

# Hacer la solicitud GET
response = requests.get(url)

# Convertir la respuesta en JSON
data = response.json()

# Mostrar los datos
data

{'code': 404}

In [62]:
import requests

# URL para obtener todas las ligas de fútbol en ESPN
url = "https://site.api.espn.com/apis/site/v2/sports/soccer"

response = requests.get(url)
data = response.json()

# Mostrar todas las ligas disponibles
print(data)

{'code': 404}

In [63]:
import requests
from bs4 import BeautifulSoup

# URL de ESPN con la lista de partidos próximos
url = "https://www.espn.com/soccer/scoreboard"

# Hacer la solicitud
response = requests.get(url)
soup = BeautifulSoup(response.text, "html.parser")

# Buscar los contenedores de partidos
partidos = soup.find_all("article", class_="Scoreboard__item")

# Extraer información de cada partido
for partido in partidos:
    equipos = partido.find_all("span", class_="ScoreCell__TeamName")
    fecha_hora = partido.find("span", class_="ScoreCell__Time")

    if equipos and fecha_hora:
        equipo_local = equipos[0].text.strip()
        equipo_visitante = equipos[1].text.strip()
        horario = fecha_hora.text.strip()
        
        print(f"{equipo_local} vs {equipo_visitante} - {horario}")

In [70]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

try:
    options = webdriver.ChromeOptions()
    options.add_argument("--headless")  # No abrir ventana
    options.add_argument("--disable-gpu")
    options.add_argument("--no-sandbox")

    driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)

    driver.get("https://www.google.com")
    print("Chrome abierto correctamente:", driver.title)
    
except Exception as e:
    print("Error:", e)

finally:
    driver.quit()

Error: Message: unknown error: cannot find Chrome binary
Stacktrace:
#0 0x5572582bb4e3 <unknown>
#1 0x557257feac76 <unknown>
#2 0x557258011757 <unknown>
#3 0x557258010029 <unknown>
#4 0x55725804eccc <unknown>
#5 0x55725804e47f <unknown>
#6 0x557258045de3 <unknown>
#7 0x55725801b2dd <unknown>
#8 0x55725801c34e <unknown>
#9 0x55725827b3e4 <unknown>
#10 0x55725827f3d7 <unknown>
#11 0x557258289b20 <unknown>
#12 0x557258280023 <unknown>
#13 0x55725824e1aa <unknown>
#14 0x5572582a46b8 <unknown>
#15 0x5572582a4847 <unknown>
#16 0x5572582b4243 <unknown>
#17 0x7fb8e364aac3 <unknown>

NameError: name 'driver' is not defined

AttributeError: 'str' object has no attribute 'capabilities'