In [5]:
from extr_numero import extraer_numero

In [11]:
import pandas as pd
import numpy as np

def extr_url_primer(urlpath):

    data = pd.read_html('https://fbref.com/es/comps/9/2019-2020/horario/Marcadores-y-partidos-de-2019-2020-Premier-League')
    data = data[0]
    for i in range(0,5):
        urlname = '202'+str(i)+'-'+'202'+str(i+1)+'/horario/Marcadores-y-partidos-de-202'+str(i)+'-202'+str(i+1)+'-Premier-League'
        url = urlpath + urlname 

        sesons_data = pd.read_html(url)
        sesons_data = sesons_data[0]
        data = pd.concat([data, sesons_data],axis=0)
    return data

In [12]:
urlpath = 'https://fbref.com/es/comps/9/'

In [45]:
data = extr_url_primer(urlpath)

In [42]:
import re
def extraer_numero(cadena):
    numeros = re.findall(r'\b\d+\b', str(cadena))
    if numeros:
        return int(numeros[0])
    else:
        return None

In [17]:
data.to_csv('../csv_o_xlxs/data_primer_league.csv')

In [19]:
data.reset_index()

,index,Sem.,Día,Fecha,Hora,Local,xG,Marcador,xG.1,Visitante,Asistencia,Sedes,Árbitro,Informe del partido,Notas
0,0,1.0,Vie,2019-08-09,20:00,Liverpool,1.8,4–1,0.9,Norwich City,53333.0,Anfield,Michael Oliver,Informe del partido,NaN
1,1,1.0,Sáb,2019-08-10,12:30,West Ham,1.1,0–5,3.2,Manchester City,59870.0,London Stadium,Mike Dean,Informe del partido,NaN
2,2,1.0,Sáb,2019-08-10,15:00,Burnley,0.9,3–0,1.2,Southampton,19784.0,Turf Moor,Graham Scott,Informe del partido,NaN
3,3,1.0,Sáb,2019-08-10,15:00,Watford,0.7,0–3,0.8,Brighton,20245.0,Vicarage Road Stadium,Craig Pawson,Informe del partido,NaN
4,4,1.0,Sáb,2019-08-10,15:00,Crystal Palace,0.9,0–0,1.1,Everton,25151.0,Selhurst Park,Jonathan Moss,Informe del partido,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2572,412,38.0,Dom,2025-05-25,16:00,Fulham,NaN,NaN,NaN,Manchester City,NaN,Craven Cottage,NaN,Cara a cara,NaN
2573,413,38.0,Dom,2025-05-25,16:00,Nott'ham Forest,NaN,NaN,NaN,Chelsea,NaN,The City Ground,NaN,Cara a cara,NaN
2574,414,38.0,Dom,2025-05-25,16:00,Manchester Utd,NaN,NaN,NaN,Aston Villa,NaN,Old Trafford,NaN,Cara a cara,NaN
2575,415,38.0,Dom,2025-05-25,16:00,Wolves,NaN,NaN,NaN,Brentford,NaN,Molineux Stadium,NaN,Cara a cara,NaN
2576,416,38.0,Dom,2025-05-25,16:00,Tottenham,NaN,NaN,NaN,Brighton,NaN,Tottenham Hotspur Stadium,NaN,Cara a cara,NaN

In [46]:
data = data.drop('Notas',axis=1)

In [32]:
data

,Sem.,Día,Fecha,Hora,Local,xG,Marcador,xG.1,Visitante,Asistencia,Sedes,Árbitro,Informe del partido
0,1.0,Vie,2019-08-09,20:00,Liverpool,1.8,4–1,0.9,Norwich City,53333.0,Anfield,Michael Oliver,Informe del partido
1,1.0,Sáb,2019-08-10,12:30,West Ham,1.1,0–5,3.2,Manchester City,59870.0,London Stadium,Mike Dean,Informe del partido
2,1.0,Sáb,2019-08-10,15:00,Burnley,0.9,3–0,1.2,Southampton,19784.0,Turf Moor,Graham Scott,Informe del partido
3,1.0,Sáb,2019-08-10,15:00,Watford,0.7,0–3,0.8,Brighton,20245.0,Vicarage Road Stadium,Craig Pawson,Informe del partido
4,1.0,Sáb,2019-08-10,15:00,Crystal Palace,0.9,0–0,1.1,Everton,25151.0,Selhurst Park,Jonathan Moss,Informe del partido
...,...,...,...,...,...,...,...,...,...,...,...,...,...
412,38.0,Dom,2025-05-25,16:00,Fulham,NaN,NaN,NaN,Manchester City,NaN,Craven Cottage,NaN,Cara a cara
413,38.0,Dom,2025-05-25,16:00,Nott'ham Forest,NaN,NaN,NaN,Chelsea,NaN,The City Ground,NaN,Cara a cara
414,38.0,Dom,2025-05-25,16:00,Manchester Utd,NaN,NaN,NaN,Aston Villa,NaN,Old Trafford,NaN,Cara a cara
415,38.0,Dom,2025-05-25,16:00,Wolves,NaN,NaN,NaN,Brentford,NaN,Molineux Stadium,NaN,Cara a cara
416,38.0,Dom,2025-05-25,16:00,Tottenham,NaN,NaN,NaN,Brighton,NaN,Tottenham Hotspur Stadium,NaN,Cara a cara

In [47]:
data = data.dropna(subset=['Sem.'])
data.head(12)

,Sem.,Día,Fecha,Hora,Local,xG,Marcador,xG.1,Visitante,Asistencia,Sedes,Árbitro,Informe del partido
0,1.0,Vie,2019-08-09,20:00,Liverpool,1.8,4–1,0.9,Norwich City,53333.0,Anfield,Michael Oliver,Informe del partido
1,1.0,Sáb,2019-08-10,12:30,West Ham,1.1,0–5,3.2,Manchester City,59870.0,London Stadium,Mike Dean,Informe del partido
2,1.0,Sáb,2019-08-10,15:00,Burnley,0.9,3–0,1.2,Southampton,19784.0,Turf Moor,Graham Scott,Informe del partido
3,1.0,Sáb,2019-08-10,15:00,Watford,0.7,0–3,0.8,Brighton,20245.0,Vicarage Road Stadium,Craig Pawson,Informe del partido
4,1.0,Sáb,2019-08-10,15:00,Crystal Palace,0.9,0–0,1.1,Everton,25151.0,Selhurst Park,Jonathan Moss,Informe del partido
5,1.0,Sáb,2019-08-10,15:00,Bournemouth,1.3,1–1,1.3,Sheffield Utd,10714.0,Vitality Stadium,Kevin Friend,Informe del partido
6,1.0,Sáb,2019-08-10,17:30,Tottenham,2.4,3–1,0.7,Aston Villa,60407.0,Tottenham Hotspur Stadium,Chris Kavanagh,Informe del partido
7,1.0,Dom,2019-08-11,14:00,Newcastle Utd,0.4,0–1,1.1,Arsenal,47635.0,St. James' Park,Martin Atkinson,Informe del partido
8,1.0,Dom,2019-08-11,14:00,Leicester City,0.7,0–0,0.7,Wolves,32015.0,King Power Stadium,Andre Marriner,Informe del partido
9,1.0,Dom,2019-08-11,16:30,Manchester Utd,2.2,4–0,1.0,Chelsea,73620.0,Old Trafford,Anthony Taylor,Informe del partido
11,2.0,Sáb,2019-08-17,12:30,Arsenal,0.8,2–1,1.5,Burnley,60214.0,Emirates Stadium,Mike Dean,Informe del partido
12,2.0,Sáb,2019-08-17,15:00,Norwich City,1.7,3–1,0.9,Newcastle Utd,27059.0,Carrow Road,Stuart Attwell,Informe del partido

In [48]:
data[['Goles Local', 'Goles Visitante']] = data['Marcador'].str.split('–', expand=True)
data = data.drop('Marcador', axis=1)
data['Goles Local'] = data['Goles Local'].apply(extraer_numero).fillna(0).astype(int)
data['Goles Visitante'] = data['Goles Visitante'].apply(extraer_numero).fillna(0).astype(int)
data = data.reset_index(drop=True)

In [50]:
data = data.dropna(subset=['Árbitro'])

In [61]:
data = data.reset_index(drop=True)

In [69]:
data.to_csv('../csv_o_xlxs/data_prime_league.csv')

In [67]:
data = data.drop('level_0',axis=1)
data = data.drop('index',axis=1)

In [68]:
data

,Sem.,Día,Fecha,Hora,Local,xG,xG.1,Visitante,Asistencia,Sedes,Árbitro,Informe del partido,Goles Local,Goles Visitante
0,1.0,Vie,2019-08-09,20:00,Liverpool,1.8,0.9,Norwich City,53333.0,Anfield,Michael Oliver,Informe del partido,4,1
1,1.0,Sáb,2019-08-10,12:30,West Ham,1.1,3.2,Manchester City,59870.0,London Stadium,Mike Dean,Informe del partido,0,5
2,1.0,Sáb,2019-08-10,15:00,Burnley,0.9,1.2,Southampton,19784.0,Turf Moor,Graham Scott,Informe del partido,3,0
3,1.0,Sáb,2019-08-10,15:00,Watford,0.7,0.8,Brighton,20245.0,Vicarage Road Stadium,Craig Pawson,Informe del partido,0,3
4,1.0,Sáb,2019-08-10,15:00,Crystal Palace,0.9,1.1,Everton,25151.0,Selhurst Park,Jonathan Moss,Informe del partido,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2084,19.0,Dom,2024-12-29,17:15,West Ham,0.4,3.1,Liverpool,62476.0,London Stadium,Anthony Taylor,Informe del partido,0,5
2085,19.0,Lun,2024-12-30,19:45,Aston Villa,1.8,1.1,Brighton,41414.0,Villa Park,Craig Pawson,Informe del partido,2,2
2086,19.0,Lun,2024-12-30,19:45,Ipswich Town,1.6,2.0,Chelsea,29968.0,Portman Road Stadium,John Brooks,Informe del partido,2,0
2087,19.0,Lun,2024-12-30,20:00,Manchester Utd,0.8,1.9,Newcastle Utd,73809.0,Old Trafford,Simon Hooper,Informe del partido,0,2
2088,19.0,Mié,2025-01-01,17:30,Brentford,0.3,1.9,Arsenal,47190.0,Gtech Community Stadium,Peter Bankes,Informe del partido,1,3

In [76]:
goles = data.groupby('Local')['Goles Local'].sum().reset_index()

In [79]:
goles[:20]

         Fecha            Local  Goles Local
0   2019-08-09        Liverpool            4
1   2019-08-10      Bournemouth            1
2   2019-08-10          Burnley            3
3   2019-08-10   Crystal Palace            0
4   2019-08-10        Tottenham            3
5   2019-08-10          Watford            0
6   2019-08-10         West Ham            0
7   2019-08-11   Leicester City            0
8   2019-08-11   Manchester Utd            4
9   2019-08-11    Newcastle Utd            0
10  2019-08-17          Arsenal            2
11  2019-08-17      Aston Villa            1
12  2019-08-17         Brighton            1
13  2019-08-17          Everton            1
14  2019-08-17  Manchester City            2
15  2019-08-17     Norwich City            3
16  2019-08-17      Southampton            1
17  2019-08-18          Chelsea            1
18  2019-08-18    Sheffield Utd            1
19  2019-08-19           Wolves            1

In [81]:
# Sumar los goles de local y visita para cada equipo
goles_local = data.groupby('Local')['Goles Local'].sum().reset_index()
goles_visitante = data.groupby('Visitante')['Goles Visitante'].sum().reset_index()

# Renombrar las columnas para identificar los goles de local y visitante
goles_local.rename(columns={'Goles Local': 'Goles'}, inplace=True)
goles_visitante.rename(columns={'Goles Visitante': 'Goles'}, inplace=True)

# Unir los goles de local y visitante para obtener el total
goles_totales = pd.concat([goles_local, goles_visitante]).groupby('Equipo')['Goles'].sum().reset_index()

KeyError: 'Equipo'

In [85]:
equipos_unicos = pd.unique(data[['Local', 'Visitante']].values.ravel())
# Crear un DataFrame con todos los equipos
equipos_data = pd.DataFrame(equipos_unicos, columns=['Equipo'])

# Calcular los goles de local
goles_local = data.groupby('Local')['Goles Local'].sum().reset_index().rename(columns={'Local': 'Equipo', 'Goles Local': 'Goles'})

# Calcular los goles de visitante
goles_visitante = data.groupby('Visitante')['Goles Visitante'].sum().reset_index().rename(columns={'Visitante': 'Equipo', 'Visitante': 'Goles'})

# Unir los goles de local y visitante
goles_totales = pd.concat([goles_local, goles_visitante]).groupby('Equipo')['Goles'].sum().reset_index()

# Asegurarse de que todos los equipos estén presentes, incluso aquellos sin goles
equipos_data = pd.merge(equipos_data, goles_totales, on='Equipo', how='left').fillna(0)

In [90]:
equipos_data.sort_values(by='Goles',ascending=False).reset_index(drop=True)

             Equipo  Goles
0   Manchester City    286
1         Liverpool    243
2           Arsenal    214
3         Tottenham    209
4    Manchester Utd    190
5       Aston Villa    178
6           Chelsea    177
7     Newcastle Utd    172
8          West Ham    165
9          Brighton    141
10   Leicester City    137
11   Crystal Palace    129
12           Wolves    127
13          Everton    122
14        Brentford    113
15      Southampton     98
16           Fulham     87
17      Bournemouth     80
18          Burnley     75
19     Leeds United     73
20  Nott'ham Forest     65
21    Sheffield Utd     55
22          Watford     39
23     Norwich City     31
24       Luton Town     28
25        West Brom     15
26     Ipswich Town      8

In [91]:
partidos_local = data.groupby('Local').size().reset_index(name='Partidos Jugados Local')

In [93]:
partidos_totales['Partidos Totales'] = partidos_totales['Partidos_Jugados_Local'] + partidos_totales['Partidos_Jugados_Visitante']

              Local  Partidos Jugados Local
0           Arsenal                     104
1       Aston Villa                     105
2       Bournemouth                      66
3         Brentford                      67
4          Brighton                     104
5           Burnley                      76
6           Chelsea                     104
7    Crystal Palace                     105
8           Everton                     104
9            Fulham                      67
10     Ipswich Town                      10
11     Leeds United                      57
12   Leicester City                      86
13        Liverpool                     104
14       Luton Town                      19
15  Manchester City                     104
16   Manchester Utd                     105
17    Newcastle Utd                     104
18     Norwich City                      38
19  Nott'ham Forest                      47
20    Sheffield Utd                      57
21      Southampton                      85
22        Tottenham                     105
23          Watford                      38
24        West Brom                      19
25         West Ham                     105
26           Wolves                     104

In [94]:
# Contar los partidos jugados como local para cada equipo
partidos_local = data.groupby('Local').size().reset_index(name='Partidos Local')

# Contar los partidos jugados como visitante para cada equipo
partidos_visitante = data.groupby('Visitante').size().reset_index(name='Partidos Visitante')

# Unir las estadísticas de partidos jugados como local y visitante
partidos_totales = pd.merge(partidos_local, partidos_visitante, left_on='Local', right_on='Visitante', how='outer')

# Renombrar las columnas para unificar
partidos_totales = partidos_totales.rename(columns={'Local': 'Equipo', 'Partidos Local': 'Partidos Jugados Local', 'Partidos Visitante': 'Partidos Jugados Visitante'})

# Calcular el total de partidos jugados por cada equipo (local + visitante)
partidos_totales['Partidos Totales'] = partidos_totales['Partidos Jugados Local'] + partidos_totales['Partidos Jugados Visitante']

In [97]:
partidos_totales=partidos_totales.drop('Partidos Jugados Local',axis=1)
partidos_totales=partidos_totales.drop('Visitante',axis=1)
partidos_totales=partidos_totales.drop('Partidos Jugados Visitante',axis=1)

In [99]:
partidos_totales.sort_values(by='Partidos Totales',ascending=False).reset_index(drop=True)

             Equipo  Partidos Totales
0           Arsenal               209
1       Aston Villa               209
2          West Ham               209
3         Tottenham               209
4     Newcastle Utd               209
5    Manchester Utd               209
6   Manchester City               209
7            Wolves               209
8          Brighton               209
9    Crystal Palace               209
10          Chelsea               209
11          Everton               208
12        Liverpool               208
13   Leicester City               171
14      Southampton               171
15          Burnley               152
16           Fulham               133
17        Brentford               133
18      Bournemouth               133
19     Leeds United               114
20    Sheffield Utd               114
21  Nott'ham Forest                95
22     Norwich City                76
23          Watford                76
24       Luton Town                38
25        West Brom                38
26     Ipswich Town                19

In [117]:
data_poisson = data[1304:1900]

In [120]:
data_poisson=data_poisson.reset_index(drop=True)

In [123]:
data_goles_local = data_poisson.groupby('Local')['Goles Local'].sum().reset_index().rename(columns={'Local': 'Equipo', 'Goles Local': 'Goles Local'})
data_goles_Visitante = data_poisson.groupby('Visitante')['Goles Visitante'].sum().reset_index().rename(columns={'Local': 'Equipo', 'Goles Local': 'Goles Local'})

In [124]:
data_goles_local

             Equipo  Goles Local
0           Arsenal           79
1       Aston Villa           69
2       Bournemouth           38
3         Brentford           49
4          Brighton           54
5           Burnley           19
6           Chelsea           52
7    Crystal Palace           48
8           Everton           31
9            Fulham           46
10     Leeds United           13
11   Leicester City           14
12        Liverpool           72
13       Luton Town           28
14  Manchester City           80
15   Manchester Utd           55
16    Newcastle Utd           68
17  Nott'ham Forest           44
18    Sheffield Utd           19
19      Southampton           10
20        Tottenham           54
21         West Ham           48
22           Wolves           40