In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

Local = IALxIDVxpromedio de Goles
Visita = IAVxIDLxpromedio de Goles

In [25]:
data = pd.read_html('https://fbref.com/es/comps/9/2022-2023/horario/Marcadores-y-partidos-de-2022-2023-Premier-League',encoding='UTF-8')
data = data[0]
data[['Goles Local', 'Goles Visitante']] = data['Marcador'].str.split('–', expand=True)
data = data.drop('Marcador', axis=1)
data['Goles Local'] = data['Goles Local'].apply(extraer_numero).fillna(0).astype(int)
data['Goles Visitante'] = data['Goles Visitante'].apply(extraer_numero).fillna(0).astype(int)
data = data.reset_index(drop=True)
equipos = pd.concat([data['Local'],data['Visitante']]).dropna()
equipos_unicos = equipos.unique()
equipos_unicos_ordenados = sorted(equipos_unicos)
equipos_unicos_ordenados

['Arsenal',
 'Aston Villa',
 'Bournemouth',
 'Brentford',
 'Brighton',
 'Chelsea',
 'Crystal Palace',
 'Everton',
 'Fulham',
 'Leeds United',
 'Leicester City',
 'Liverpool',
 'Manchester City',
 'Manchester Utd',
 'Newcastle Utd',
 "Nott'ham Forest",
 'Southampton',
 'Tottenham',
 'West Ham',
 'Wolves']

In [34]:
data = data.drop('Notas',axis=1)
data = data.drop('xG',axis=1)
data = data.drop('xG.1',axis=1)
data[:20]

KeyError: "['Notas'] not found in axis"

In [32]:
# Goles a favor como local y visitante
goles_favor_local = data.groupby("Local")["Goles Local"].sum()
goles_favor_visitante = data.groupby("Visitante")["Goles Visitante"].sum()
goles_a_favor = goles_favor_local.add(goles_favor_visitante, fill_value=0)

# Goles en contra como local y visitante
goles_contra_local = data.groupby("Local")["Goles Visitante"].sum()
goles_contra_visitante = data.groupby("Visitante")["Goles Local"].sum()
goles_en_contra = goles_contra_local.add(goles_contra_visitante, fill_value=0)

In [33]:
data1 = {

    'Equipo':equipos_unicos_ordenados,
    '# Partidos':[18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18],
    'Goles a Favor': goles_a_favor,
    'Goles en Contra': goles_en_contra
    
}

pd.DataFrame(data1)

                          Equipo  # Partidos  Goles a Favor  Goles en Contra
Local
Arsenal                  Arsenal          18             88               43
Aston Villa          Aston Villa          18             51               46
Bournemouth          Bournemouth          18             37               71
Brentford              Brentford          18             58               46
Brighton                Brighton          18             72               53
Chelsea                  Chelsea          18             38               47
Crystal Palace    Crystal Palace          18             40               49
Everton                  Everton          18             34               57
Fulham                    Fulham          18             55               53
Leeds United        Leeds United          18             48               78
Leicester City    Leicester City          18             51               68
Liverpool              Liverpool          18             75               47
Manchester City  Manchester City          18             94               33
Manchester Utd    Manchester Utd          18             58               43
Newcastle Utd      Newcastle Utd          18             68               33
Nott'ham Forest  Nott'ham Forest          18             38               68
Southampton          Southampton          18             36               73
Tottenham              Tottenham          18             70               63
West Ham                West Ham          18             42               55
Wolves                    Wolves          18             31               58

In [2]:
data_primer = pd.read_csv('../csv_o_xlxs/data_prime_league.csv')

In [3]:
data_primer

,Unnamed: 0,Sem.,Día,Fecha,Hora,Local,xG,xG.1,Visitante,Asistencia,Sedes,Árbitro,Informe del partido,Goles Local,Goles Visitante
0,0,1.0,Vie,2019-08-09,20:00,Liverpool,1.8,0.9,Norwich City,53333.0,Anfield,Michael Oliver,Informe del partido,4,1
1,1,1.0,Sáb,2019-08-10,12:30,West Ham,1.1,3.2,Manchester City,59870.0,London Stadium,Mike Dean,Informe del partido,0,5
2,2,1.0,Sáb,2019-08-10,15:00,Burnley,0.9,1.2,Southampton,19784.0,Turf Moor,Graham Scott,Informe del partido,3,0
3,3,1.0,Sáb,2019-08-10,15:00,Watford,0.7,0.8,Brighton,20245.0,Vicarage Road Stadium,Craig Pawson,Informe del partido,0,3
4,4,1.0,Sáb,2019-08-10,15:00,Crystal Palace,0.9,1.1,Everton,25151.0,Selhurst Park,Jonathan Moss,Informe del partido,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2093,2093,20.0,Sáb,2025-01-04,15:00,Manchester City,1.9,1.4,West Ham,52737.0,Etihad Stadium,Michael Salisbury,Informe del partido,4,1
2094,2094,20.0,Sáb,2025-01-04,15:00,Aston Villa,1.4,0.4,Leicester City,42386.0,Villa Park,Jarred Gillett,Informe del partido,2,1
2095,2095,20.0,Sáb,2025-01-04,17:30,Brighton,1.5,0.9,Arsenal,31714.0,The American Express Stadium,Anthony Taylor,Informe del partido,1,1
2096,2096,20.0,Dom,2025-01-05,14:00,Fulham,2.2,1.5,Ipswich Town,NaN,Craven Cottage,Darren Bond,Informe del partido,2,2
2097,2097,20.0,Dom,2025-01-05,16:30,Liverpool,2.7,1.0,Manchester Utd,NaN,Anfield,Michael Oliver,Informe del partido,2,2

In [4]:
goles_favor_local = data_primer.groupby("Local")["Goles Local"].sum()
goles_favor_visitante = data_primer.groupby("Visitante")["Goles Visitante"].sum()
goles_a_favor = goles_favor_local.add(goles_favor_visitante, fill_value=0)

# Goles en contra como local y visitante
goles_contra_local = data_primer.groupby("Local")["Goles Visitante"].sum()
goles_contra_visitante = data_primer.groupby("Visitante")["Goles Local"].sum()
goles_en_contra = goles_contra_local.add(goles_contra_visitante, fill_value=0)

In [7]:
equipos = pd.concat([data_primer['Local'],data_primer['Visitante']]).dropna()
equipos_unicos = equipos.unique()
equipos_unicos_ordenados = sorted(equipos_unicos)
len(equipos_unicos_ordenados)

27

In [13]:
data1 = {

    'Equipo':equipos_unicos_ordenados,
    '# Partidos':[18 for i in range(0,27)],
    'Goles a Favor': goles_a_favor,
    'Goles en Contra': goles_en_contra
    
}

pd.DataFrame(data1)

                          Equipo  # Partidos  Goles a Favor  Goles en Contra
Local
Arsenal                  Arsenal          18            390              225
Aston Villa          Aston Villa          18            305              306
Bournemouth          Bournemouth          18            161              226
Brentford              Brentford          18            200              202
Brighton                Brighton          18            278              288
Burnley                  Burnley          18            151              236
Chelsea                  Chelsea          18            357              257
Crystal Palace    Crystal Palace          18            240              297
Everton                  Everton          18            223              303
Fulham                    Fulham          18            167              194
Ipswich Town        Ipswich Town          18             20               35
Leeds United        Leeds United          18            152              211
Leicester City    Leicester City          18            271              262
Liverpool              Liverpool          18            455              208
Luton Town            Luton Town          18             52               85
Manchester City  Manchester City          18            510              187
Manchester Utd    Manchester Utd          18            334              266
Newcastle Utd      Newcastle Utd          18            315              299
Norwich City        Norwich City          18             49              159
Nott'ham Forest  Nott'ham Forest          18            113              154
Sheffield Utd      Sheffield Utd          18             94              206
Southampton          Southampton          18            189              312
Tottenham              Tottenham          18            384              286
Watford                  Watford          18             70              141
West Brom              West Brom          18             35               76
West Ham                West Ham          18            297              328
Wolves                    Wolves          18            237              300

In [15]:
['Hola' for i in range(0, 27) if i % 2 == 0]

['Hola',
 'Hola',
 'Hola',
 'Hola',
 'Hola',
 'Hola',
 'Hola',
 'Hola',
 'Hola',
 'Hola',
 'Hola',
 'Hola',
 'Hola',
 'Hola']

In [16]:
['Hola' if i % 2 == 0 else 'Adiós' for i in range(0, 27)]

['Hola',
 'Adiós',
 'Hola',
 'Adiós',
 'Hola',
 'Adiós',
 'Hola',
 'Adiós',
 'Hola',
 'Adiós',
 'Hola',
 'Adiós',
 'Hola',
 'Adiós',
 'Hola',
 'Adiós',
 'Hola',
 'Adiós',
 'Hola',
 'Adiós',
 'Hola',
 'Adiós',
 'Hola',
 'Adiós',
 'Hola',
 'Adiós',
 'Hola']

In [ ]:
equipos_locales = data_primer[['temporada', 'home_team']].rename(columns={'home_team': 'team'})
equipos_visitantes = data_primer[['temporada', 'away_team']].rename(columns={'away_team': 'team'})

# Unificar todos los equipos
equipos_totales = pd.concat([equipos_locales, equipos_visitantes])

In [17]:
data_primer['Fecha'] = pd.to_datetime(data_primer['Fecha'])

# Crear la columna de temporada
data_primer['temporada'] = data_primer['Fecha'].apply(lambda x: f"{x.year}-{x.year+1}" if x.month >= 8 else f"{x.year-1}-{x.year}")

In [24]:
data_primer

,Sem.,Día,Fecha,Hora,Local,xG,xG.1,Visitante,Asistencia,Sedes,Árbitro,Informe del partido,Goles Local,Goles Visitante,temporada
0,1.0,Vie,2019-08-09,20:00,Liverpool,1.8,0.9,Norwich City,53333.0,Anfield,Michael Oliver,Informe del partido,4,1,2019-2020
1,1.0,Sáb,2019-08-10,12:30,West Ham,1.1,3.2,Manchester City,59870.0,London Stadium,Mike Dean,Informe del partido,0,5,2019-2020
2,1.0,Sáb,2019-08-10,15:00,Burnley,0.9,1.2,Southampton,19784.0,Turf Moor,Graham Scott,Informe del partido,3,0,2019-2020
3,1.0,Sáb,2019-08-10,15:00,Watford,0.7,0.8,Brighton,20245.0,Vicarage Road Stadium,Craig Pawson,Informe del partido,0,3,2019-2020
4,1.0,Sáb,2019-08-10,15:00,Crystal Palace,0.9,1.1,Everton,25151.0,Selhurst Park,Jonathan Moss,Informe del partido,0,0,2019-2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2093,20.0,Sáb,2025-01-04,15:00,Manchester City,1.9,1.4,West Ham,52737.0,Etihad Stadium,Michael Salisbury,Informe del partido,4,1,2024-2025
2094,20.0,Sáb,2025-01-04,15:00,Aston Villa,1.4,0.4,Leicester City,42386.0,Villa Park,Jarred Gillett,Informe del partido,2,1,2024-2025
2095,20.0,Sáb,2025-01-04,17:30,Brighton,1.5,0.9,Arsenal,31714.0,The American Express Stadium,Anthony Taylor,Informe del partido,1,1,2024-2025
2096,20.0,Dom,2025-01-05,14:00,Fulham,2.2,1.5,Ipswich Town,NaN,Craven Cottage,Darren Bond,Informe del partido,2,2,2024-2025
2097,20.0,Dom,2025-01-05,16:30,Liverpool,2.7,1.0,Manchester Utd,NaN,Anfield,Michael Oliver,Informe del partido,2,2,2024-2025

In [30]:
equipos_locales = data_primer[['temporada', 'Local']].rename(columns={'Local': 'equipo'})
equipos_visitantes = data_primer[['temporada', 'Visitante']].rename(columns={'Visitante': 'equipo'})

goles_locales = data_primer[['temporada', 'Goles Local']].rename(columns={'Local': 'Goles Local'})
goles_visitantes = data_primer[['temporada', 'Goles Visitante']].rename(columns={'Visitante': 'Goles Visitante'})

goles_visitantes = data_primer.groupby(['temporada', 'Visitante'])['Goles Visitante'].sum().reset_index()
goles_visitantes.rename(columns={'Visitante': 'team', 'Visitante': 'goles_anotados'}, inplace=True)

goles_locales = data_primer.groupby(['temporada', 'Local'])['Goles Local'].sum().reset_index()
goles_locales.rename(columns={'Local': 'team', 'Local': 'goles_anotados'}, inplace=True)


# Unificar todos los equipos
equipos_totales = pd.concat([equipos_locales, equipos_visitantes])
# Contar partidos jugados por equipo en cada temporada
partidos_por_equipo = equipos_totales.groupby(['temporada', 'equipo']).size().reset_index(name='partidos jugados')

     temporada           equipo  partidos jugados
0    2019-2020          Arsenal                38
1    2019-2020      Aston Villa                38
2    2019-2020      Bournemouth                38
3    2019-2020         Brighton                38
4    2019-2020          Burnley                38
..         ...              ...               ...
115  2024-2025  Nott'ham Forest                19
116  2024-2025      Southampton                20
117  2024-2025        Tottenham                20
118  2024-2025         West Ham                20
119  2024-2025           Wolves                19

[120 rows x 3 columns]

In [31]:
# Agrupar goles por equipo como local
goles_locales = data_primer.groupby(['temporada', 'Local'])['Goles Local'].sum().reset_index()
goles_locales.rename(columns={'Local': 'team', 'Goles Local': 'goles_anotados'}, inplace=True)

# Agrupar goles por equipo como visitante
goles_visitantes = data_primer.groupby(['temporada', 'Visitante'])['Goles Visitante'].sum().reset_index()
goles_visitantes.rename(columns={'Visitante': 'team', 'Goles Visitante': 'goles_anotados'}, inplace=True)

# Unificar los goles de locales y visitantes
goles_totales = pd.concat([goles_locales, goles_visitantes])

# Sumar los goles totales por equipo y temporada
goles_por_equipo = goles_totales.groupby(['temporada', 'team'])['goles_anotados'].sum().reset_index()

# Ahora 'goles_por_equipo' tiene los goles por equipo en cada temporada
print(goles_por_equipo)

     temporada             team  goles_anotados
0    2019-2020          Arsenal              56
1    2019-2020      Aston Villa              41
2    2019-2020      Bournemouth              40
3    2019-2020         Brighton              39
4    2019-2020          Burnley              43
..         ...              ...             ...
115  2024-2025  Nott'ham Forest              26
116  2024-2025      Southampton              12
117  2024-2025        Tottenham              42
118  2024-2025         West Ham              24
119  2024-2025           Wolves              31

[120 rows x 3 columns]

In [33]:
# Crear la lista de todos los equipos (locales y visitantes)
equipos_locales = data_primer[['temporada', 'Local']].rename(columns={'Local': 'equipo'})
equipos_visitantes = data_primer[['temporada', 'Visitante']].rename(columns={'Visitante': 'equipo'})

# Unificar todos los equipos en un solo DataFrame
equipos_totales = pd.concat([equipos_locales, equipos_visitantes])

# Contar partidos jugados por equipo en cada temporada
partidos_por_equipo = equipos_totales.groupby(['temporada', 'equipo']).size().reset_index(name='partidos_jugados')

# Unir los goles por equipo con los partidos jugados
df_final = pd.merge(partidos_por_equipo, goles_por_equipo, left_on=['temporada', 'equipo'], right_on=['temporada', 'team'], how='left')

# Limpiar columnas innecesarias
df_final.drop(columns=['team'], inplace=True)

df_final

     temporada           equipo  partidos_jugados  goles_anotados
0    2019-2020          Arsenal                38              56
1    2019-2020      Aston Villa                38              41
2    2019-2020      Bournemouth                38              40
3    2019-2020         Brighton                38              39
4    2019-2020          Burnley                38              43
..         ...              ...               ...             ...
115  2024-2025  Nott'ham Forest                19              26
116  2024-2025      Southampton                20              12
117  2024-2025        Tottenham                20              42
118  2024-2025         West Ham                20              24
119  2024-2025           Wolves                19              31

[120 rows x 4 columns]

In [36]:
# Agrupar goles como local
goles_locales = data_primer.groupby(['temporada', 'Local'])['Goles Local'].sum().reset_index()
goles_locales.rename(columns={'Local': 'team', 'Goles Local': 'goles_local'}, inplace=True)

# Agrupar goles como visitante
goles_visitantes = data_primer.groupby(['temporada', 'Visitante'])['Goles Visitante'].sum().reset_index()
goles_visitantes.rename(columns={'Visitante': 'team', 'Goles Visitante': 'goles_visitante'}, inplace=True)

# Unificar goles locales y visitantes
goles_totales = pd.concat([goles_locales, goles_visitantes])

# Sumar los goles totales por equipo y temporada
goles_por_equipo = goles_totales.groupby(['temporada', 'team']).sum().reset_index()

# Calcular goles en contra (recibidos) como local
goles_en_contra_local = data_primer.groupby(['temporada', 'Visitante'])['Goles Visitante'].sum().reset_index()
goles_en_contra_local.rename(columns={'Visitante': 'team', 'Goles Visitante': 'goles_en_contra'}, inplace=True)

# Calcular goles en contra (recibidos) como visitante
goles_en_contra_visitante = data_primer.groupby(['temporada', 'Local'])['Goles Local'].sum().reset_index()
goles_en_contra_visitante.rename(columns={'Local': 'team', 'Goles Local': 'goles_en_contra'}, inplace=True)

# Unificar goles en contra (local y visitante)
goles_en_contra = pd.concat([goles_en_contra_local, goles_en_contra_visitante])

# Sumar los goles en contra por equipo y temporada
goles_en_contra_totales = goles_en_contra.groupby(['temporada', 'team'])['goles_en_contra'].sum().reset_index()

# Unir toda la información en un solo DataFrame
df_final = pd.merge(goles_por_equipo, goles_en_contra_totales, on=['temporada', 'team'], how='left')

# Contar los partidos jugados por equipo
equipos_locales = data_primer[['temporada', 'Local']].rename(columns={'Local': 'equipo'})
equipos_visitantes = data_primer[['temporada', 'Visitante']].rename(columns={'Visitante': 'equipo'})
equipos_totales = pd.concat([equipos_locales, equipos_visitantes])

# Contar partidos jugados
partidos_por_equipo = equipos_totales.groupby(['temporada', 'equipo']).size().reset_index(name='partidos_jugados')

# Unir partidos jugados con goles
df_final = pd.merge(df_final, partidos_por_equipo, left_on=['temporada', 'team'], right_on=['temporada', 'equipo'], how='left')

# Limpiar columnas
df_final.drop(columns=['equipo'], inplace=True)

# Mostrar el resultado final
df_final

,temporada,team,goles_local,goles_visitante,goles_en_contra,partidos_jugados
0,2019-2020,Arsenal,36.0,20.0,56,38
1,2019-2020,Aston Villa,22.0,19.0,41,38
2,2019-2020,Bournemouth,22.0,18.0,40,38
3,2019-2020,Brighton,20.0,19.0,39,38
4,2019-2020,Burnley,24.0,19.0,43,38
...,...,...,...,...,...,...
115,2024-2025,Nott'ham Forest,11.0,15.0,26,19
116,2024-2025,Southampton,7.0,5.0,12,20
117,2024-2025,Tottenham,26.0,16.0,42,20
118,2024-2025,West Ham,13.0,11.0,24,20
119,2024-2025,Wolves,14.0,17.0,31,19

In [39]:
data_primer

,Sem.,Día,Fecha,Hora,Local,xG,xG.1,Visitante,Asistencia,Sedes,Árbitro,Informe del partido,Goles Local,Goles Visitante,temporada
0,1.0,Vie,2019-08-09,20:00,Liverpool,1.8,0.9,Norwich City,53333.0,Anfield,Michael Oliver,Informe del partido,4,1,2019-2020
1,1.0,Sáb,2019-08-10,12:30,West Ham,1.1,3.2,Manchester City,59870.0,London Stadium,Mike Dean,Informe del partido,0,5,2019-2020
2,1.0,Sáb,2019-08-10,15:00,Burnley,0.9,1.2,Southampton,19784.0,Turf Moor,Graham Scott,Informe del partido,3,0,2019-2020
3,1.0,Sáb,2019-08-10,15:00,Watford,0.7,0.8,Brighton,20245.0,Vicarage Road Stadium,Craig Pawson,Informe del partido,0,3,2019-2020
4,1.0,Sáb,2019-08-10,15:00,Crystal Palace,0.9,1.1,Everton,25151.0,Selhurst Park,Jonathan Moss,Informe del partido,0,0,2019-2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2093,20.0,Sáb,2025-01-04,15:00,Manchester City,1.9,1.4,West Ham,52737.0,Etihad Stadium,Michael Salisbury,Informe del partido,4,1,2024-2025
2094,20.0,Sáb,2025-01-04,15:00,Aston Villa,1.4,0.4,Leicester City,42386.0,Villa Park,Jarred Gillett,Informe del partido,2,1,2024-2025
2095,20.0,Sáb,2025-01-04,17:30,Brighton,1.5,0.9,Arsenal,31714.0,The American Express Stadium,Anthony Taylor,Informe del partido,1,1,2024-2025
2096,20.0,Dom,2025-01-05,14:00,Fulham,2.2,1.5,Ipswich Town,NaN,Craven Cottage,Darren Bond,Informe del partido,2,2,2024-2025
2097,20.0,Dom,2025-01-05,16:30,Liverpool,2.7,1.0,Manchester Utd,NaN,Anfield,Michael Oliver,Informe del partido,2,2,2024-2025