In [19]:
import pandas as pd
data_2023_2024=pd.read_html("https://fbref.com/es/comps/9/horario/Resultados-y-partidos-en-Premier-League", encoding = 'UTF-8')
data = pd.read_htmldata_2022_2023=pd.read_html("https://fbref.com/es/comps/9/2022-2023/horario/Marcadores-y-partidos-de-2022-2023-Premier-League", encoding = 'UTF-8')

data = data[0]
data_2023_2024 = data_2023_2024[0]

#unir dataframes
df = [data,data_2023_2024]
df = pd.concat(df)

#agregar columnas de goles locales y goles visita
df[['Goles Local','Goles Visita']] = df['Marcador'].str.split('–', expand=True)
#Eliminar la columna de Marcador
data = df.drop('Marcador', axis=1)


import re
def extraer_numero(cadena):
    numeros = re.findall(r'\b\d+\b', str(cadena))
    if numeros:
        return int(numeros[0])
    else:
        return None
    
data['Goles Local'] = data['Goles Local'].apply(extraer_numero).fillna(0).astype(int)
data['Goles Visita'] = data['Goles Visita'].apply(extraer_numero).fillna(0).astype(int)

data = data.reset_index(drop=True)

data

,Sem.,Día,Fecha,Hora,Local,xG,xG.1,Visitante,Asistencia,Sedes,Árbitro,Informe del partido,Notas,Goles Local,Goles Visita
0,1.0,Vie,2022-08-05,20:00,Crystal Palace,1.2,1.0,Arsenal,25286.0,Selhurst Park,Anthony Taylor,Informe del partido,NaN,0,2
1,1.0,Sáb,2022-08-06,12:30,Fulham,1.2,1.2,Liverpool,22207.0,Craven Cottage,Andy Madley,Informe del partido,NaN,2,2
2,1.0,Sáb,2022-08-06,15:00,Tottenham,1.5,0.5,Southampton,61732.0,Tottenham Hotspur Stadium,Andre Marriner,Informe del partido,NaN,4,1
3,1.0,Sáb,2022-08-06,15:00,Newcastle Utd,1.7,0.3,Nott'ham Forest,52245.0,St James' Park,Simon Hooper,Informe del partido,NaN,2,0
4,1.0,Sáb,2022-08-06,15:00,Leeds United,0.8,1.3,Wolves,36347.0,Elland Road,Robert Jones,Informe del partido,NaN,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
842,38.0,Dom,2025-05-25,16:00,Fulham,NaN,NaN,Manchester City,NaN,Craven Cottage,NaN,Cara a cara,NaN,0,0
843,38.0,Dom,2025-05-25,16:00,Nott'ham Forest,NaN,NaN,Chelsea,NaN,The City Ground,NaN,Cara a cara,NaN,0,0
844,38.0,Dom,2025-05-25,16:00,Manchester Utd,NaN,NaN,Aston Villa,NaN,Old Trafford,NaN,Cara a cara,NaN,0,0
845,38.0,Dom,2025-05-25,16:00,Wolves,NaN,NaN,Brentford,NaN,Molineux Stadium,NaN,Cara a cara,NaN,0,0
846,38.0,Dom,2025-05-25,16:00,Tottenham,NaN,NaN,Brighton,NaN,Tottenham Hotspur Stadium,NaN,Cara a cara,NaN,0,0

In [21]:
data = data.drop('xG', axis=1)
data = data.drop('xG.1',axis=1)
data = data.drop('Notas',axis=1)
data

KeyError: "['xG'] not found in axis"

In [22]:
data['Asistencia'] = data['Asistencia'].fillna(False)

In [23]:
data

,Sem.,Día,Fecha,Hora,Local,Visitante,Asistencia,Sedes,Árbitro,Informe del partido,Goles Local,Goles Visita
0,1.0,Vie,2022-08-05,20:00,Crystal Palace,Arsenal,25286.0,Selhurst Park,Anthony Taylor,Informe del partido,0,2
1,1.0,Sáb,2022-08-06,12:30,Fulham,Liverpool,22207.0,Craven Cottage,Andy Madley,Informe del partido,2,2
2,1.0,Sáb,2022-08-06,15:00,Tottenham,Southampton,61732.0,Tottenham Hotspur Stadium,Andre Marriner,Informe del partido,4,1
3,1.0,Sáb,2022-08-06,15:00,Newcastle Utd,Nott'ham Forest,52245.0,St James' Park,Simon Hooper,Informe del partido,2,0
4,1.0,Sáb,2022-08-06,15:00,Leeds United,Wolves,36347.0,Elland Road,Robert Jones,Informe del partido,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...
842,38.0,Dom,2025-05-25,16:00,Fulham,Manchester City,False,Craven Cottage,NaN,Cara a cara,0,0
843,38.0,Dom,2025-05-25,16:00,Nott'ham Forest,Chelsea,False,The City Ground,NaN,Cara a cara,0,0
844,38.0,Dom,2025-05-25,16:00,Manchester Utd,Aston Villa,False,Old Trafford,NaN,Cara a cara,0,0
845,38.0,Dom,2025-05-25,16:00,Wolves,Brentford,False,Molineux Stadium,NaN,Cara a cara,0,0
846,38.0,Dom,2025-05-25,16:00,Tottenham,Brighton,False,Tottenham Hotspur Stadium,NaN,Cara a cara,0,0

In [29]:
data[:430]

,Sem.,Día,Fecha,Hora,Local,Visitante,Asistencia,Sedes,Árbitro,Informe del partido,Goles Local,Goles Visita
0,1.0,Vie,2022-08-05,20:00,Crystal Palace,Arsenal,25286.0,Selhurst Park,Anthony Taylor,Informe del partido,0,2
1,1.0,Sáb,2022-08-06,12:30,Fulham,Liverpool,22207.0,Craven Cottage,Andy Madley,Informe del partido,2,2
2,1.0,Sáb,2022-08-06,15:00,Tottenham,Southampton,61732.0,Tottenham Hotspur Stadium,Andre Marriner,Informe del partido,4,1
3,1.0,Sáb,2022-08-06,15:00,Newcastle Utd,Nott'ham Forest,52245.0,St James' Park,Simon Hooper,Informe del partido,2,0
4,1.0,Sáb,2022-08-06,15:00,Leeds United,Wolves,36347.0,Elland Road,Robert Jones,Informe del partido,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...
425,38.0,Dom,2023-05-28,16:30,Everton,Bournemouth,39201.0,Goodison Park,Stuart Attwell,Informe del partido,1,0
426,38.0,Dom,2023-05-28,16:30,Leicester City,West Ham,32183.0,King Power Stadium,Simon Hooper,Informe del partido,2,1
427,38.0,Dom,2023-05-28,16:30,Aston Villa,Brighton,False,Villa Park,David Coote,Informe del partido,2,1
428,38.0,Dom,2023-05-28,16:30,Leeds United,Tottenham,36871.0,Elland Road,Anthony Taylor,Informe del partido,1,4
429,38.0,Dom,2023-05-28,16:30,Brentford,Manchester City,17120.0,Brentford Community Stadium,John Brooks,Informe del partido,1,0

In [ ]:
data = data[(data["Sem."] != 0) & (data["Goles Local"] != 0)]